# Generated by Django 3.0.8 on 2021-02-18 06:45

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='mydata', max_length=100)),
                ('json_data', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
